# Marco conceptual

Internet nace a partir de diversos avances tras su origen en 1947 y hoy en día es una herramienta fundamental para muchos de nosotros que ha cambiado nuestra forma de actuar, de comunicarnos y de trabajar. Profundos cambios económicos y socioculturales, mejora en las comunicaciones, expansión del conocimiento e incluso cambios en la conducta de las personas han venido de la mano de Internet. Actualmente, la vida sin internet es casi inconcebible a todos los niveles, a pesar de que en un primer momento estaba basada en una tecnología poco accesible y difícil de utilizar que requería el conocimiento de expertos. Con su evolución se fue volviendo más accesible, se desarrollaron protocolos estandarizados y surgieron nuevas aplicaciones con interfaces sencillas. Hoy en día todos tenemos un teléfono móvil con conexión a internet, y sabemos acceder a cualquier tipo de información online sin la necesidad de entender el funcionamiento interno del teléfono ni de las señales que nos brindan el internet.

Dentro de este contexto, las bases de datos se han convertido en una herramienta clave, surgiendo la necesidad de crear sistemas de almacenamiento eficaces. Hasta día de hoy, dichos sistemas estaban centralizados y tenían grandes gastos de mantenimiento, hasta que aparecio Blockchain en 2008; una gran base de datos que, a diferencia del resto, no se encuentra en un sitio fijo ni es controlada por un ente centralizado. Esta está distribuida por todo el mundo en diferentes nodos o servidores.